# -*- coding: utf-8 -*-
"""2023CaloriesBurntPredictions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vlGubAQ5h85GLiyVT7wRnTf57KkpxX0S

#***Import Dependencies***
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from xgboost import XGBRegressor

"""#***Data Collection and Preprocessing***"""

data=pd.read_csv("data.csv")

data.head()

dataa=pd.read_csv("exercise.csv")

dataa.head()

"""***Combining Two DataFrames***"""

data=pd.concat([dataa,data['Calories']],axis=1)
data.head()

data.shape

data.info()

"""***Data Analysis***"""

data.describe()

data.isnull().sum()

"""#***Data Visualization***"""

sns.displot(data['Age'])

sns.displot(data['Height'])

sns.displot(data['Weight'])

"""#***Correlation***"""

correlation=data.corr()

plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

data.replace({"Gender":{'male':0,'female':1}}, inplace=True)

"""#***Separatin Features and Target***"""

X=data.drop(columns=['User_ID','Calories'],axis=1)
Y=data['Calories']

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

"""#***Model Training***"""

model=XGBRegressor()

model.fit(X_train,X_train)

"""***Evalution***"""

prediction=model.predict(X_test)
print(prediction)